# Secret Scanning Exclusions
# These paths contain test data/patterns that look like secrets but are false positives
paths-ignore:
  - "sonar-java/**/src/test/resources/**/*"
  - "sonar-java/**/src/test/java/**/*"
  - "packages/database/prisma/migrations/**/*"
