# start_local_stack.ps1
# One-command local runtime bootstrap (without local gateway).
# Keeps Render gateway canonical and starts local backend dependencies only.

param(
    [switch]$SkipBuild
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$services = @(
    "postgres",
    "redis",
    "qdrant",
    "sonarqube",
    "sonar-scanner",
    "ai-core"
)

function Wait-HttpOk {
    param(
        [Parameter(Mandatory = $true)][string]$Url,
        [int]$TimeoutSeconds = 180
    )

    $deadline = (Get-Date).AddSeconds($TimeoutSeconds)
    while ((Get-Date) -lt $deadline) {
        try {
            $resp = Invoke-WebRequest -Uri $Url -UseBasicParsing -TimeoutSec 8
            if ($resp.StatusCode -eq 200) {
                return $true
            }
        } catch {
            # keep retrying
        }
        Start-Sleep -Seconds 2
    }
    return $false
}

Write-Host "Starting local backend stack (no local gateway)..." -ForegroundColor Cyan

# Ensure we never accidentally run local gateway in this workflow.
cmd /c "docker compose stop gateway >NUL 2>NUL"

$buildFlag = if ($SkipBuild) { "" } else { "--build" }
$cmd = "docker compose up -d $buildFlag " + ($services -join " ")
cmd /c $cmd
if ($LASTEXITCODE -ne 0) {
    throw "Failed to start docker services."
}

Write-Host "Waiting for core services..." -ForegroundColor Cyan
$aiOk = Wait-HttpOk -Url "http://localhost:3000/health" -TimeoutSeconds 240
$scannerOk = Wait-HttpOk -Url "http://localhost:8001/health" -TimeoutSeconds 180
$sonarOk = Wait-HttpOk -Url "http://localhost:9000/api/system/status" -TimeoutSeconds 300

$statusLines = @(
    "AI Core health: " + ($(if ($aiOk) { "OK" } else { "FAILED" })),
    "Sonar Scanner health: " + ($(if ($scannerOk) { "OK" } else { "FAILED" })),
    "SonarQube status API: " + ($(if ($sonarOk) { "OK" } else { "FAILED" }))
)

$runtimePath = Join-Path (Get-Location) "runtime.md"
$doc = @()
$doc += "# Runtime Targets"
$doc += "# Generated by start_local_stack.ps1 at $(Get-Date -Format s)"
$doc += ""
$doc += "## Canonical Gateway (Render)"
$doc += "GATEWAY_URL=https://testpilot-64v5.onrender.com"
$doc += ""
$doc += "## Local Backend Services"
$doc += "AI_CORE_LOCAL=http://localhost:3000"
$doc += "SONAR_SCANNER_LOCAL=http://localhost:8001"
$doc += "SONARQUBE_LOCAL=http://localhost:9000"
$doc += ""
$doc += "## VS Code Extension Setting"
$doc += "testpilot.backendUrl=https://testpilot-64v5.onrender.com"
$doc += ""
$doc += "## Frontend Hostable Env"
$doc += "NEXT_PUBLIC_BACKEND_URL=https://testpilot-64v5.onrender.com"
$doc += ""
$doc += "## Notes"
$doc += "- This startup intentionally does NOT run local gateway."
$doc += "- This startup intentionally does NOT create tunnels."
$doc += "- If Render gateway already has your tunnel envs, no retunnel is required on this laptop."
$doc += ""
$doc += "## Health"
$doc += $statusLines

Set-Content -Path $runtimePath -Value ($doc -join "`r`n")

Write-Host ""
Write-Host "Local stack started (gateway excluded)." -ForegroundColor Green
foreach ($line in $statusLines) { Write-Host $line }
Write-Host "Runtime guide written: $runtimePath"

if (-not ($aiOk -and $scannerOk -and $sonarOk)) {
    Write-Host "One or more services are not healthy yet. Check: docker compose ps and container logs." -ForegroundColor Yellow
    exit 1
}
